### PR TITLE
Update MaintenanceModeExtension.php

### PR DESCRIPTION
**Pull request by martinduparc**
Better layout for the Settings/access tab

### CODE REVIEW

**Comment by mattrayner** [comment]
Hi Martin,
 Thanks for your pull request!

Our concern about this is that, although it's more concise, we feel it makes the code less readable - potentially increasing the barrier to entry for developers that are less experienced?

Other than for conciseness, is there any other reason you feel this should be merged?

Thanks,
Matt

**Comment by martinduparc** [comment]
Hi Matt,

The main problem this PR is fixing is layout in the CMS.
Here is before:
before

Here is after:
after

We can definitely make the code more readable by adding line breaks if it helps.

Thanks!

**Comment by mattrayner** [comment]
Hi Martin,
 I see what you mean now!

If you could break the code up to make it a little more readable we'll happily merge in!

**Comment by dljoseph** [comment]
Perhaps you could simply change the `$headingLevel = 3` in the original code to `$headingLevel = 4` - that will make it fit and break up the layout enough to make it stand out as a separate section.  Thoughts?

**Comment by martinduparc** [comment]
@mattrayner I've updated my branch wth additional line breaks. 

@dljoseph I think it integrates better if it follows the existing layout but I get what you're saying. I've also tried to follow what SilverStripe does "natively". See https://github.com/silverstripe/silverstripe-cms/blob/master/code/model/SiteTree.php#L1922 and https://github.com/silverstripe/silverstripe-cms/blob/master/code/model/SiteTree.php#L1950

**Comment by mattrayner** [comment]
@martinduparc Thanks for making those changes - merged appreciatively 👍

**Pull request merged**
